### ISSUE TITLE
Is there a reason to put anyone Windows side through the 3 hour install process?

### ISSUE THREAD

**Issue by dlstrong** [data-carpentry-for-agriculture/trial-lesson#16]
Given a choice between

a) Fumble through downloading 5 Gb over a home network and spending 3-4 hours running installation scripts after that
or
b) Copy an already running installation off a USB drive in about 15-30 minutes

Is there still any reason to ask anyone for preinstall?

We should write the instructions for anyone we're not teaching personally, so that they're available on the web. But for people who will be learning directly from us, is there a reason not to go all USB?

**Comment by lvclark** [comment]
Building confidence that one can do it all from scratch? The possibility
that the USB stick won't work for everyone?

**Comment by dlstrong** [comment]
Good points! 

I can't say that my own experience was confidence-building, even with 2 experts in the room and 20 years of software-installation experience, but the "belt, suspenders, and duct tape" approach does suggest having all three available. 

I just don't know if we want to _recommend_ it to people who may be coming in frustrated and uncomfortable if that kind of unsupported hands-on multi-hour fight was their first encounter with what we want to teach them.

**Comment by dlstrong** [comment]
Going to mark this resolved since we're going with instruction sets that let them choose whether they want to run from USB, copy from USB, or direct install in advance.
