### ISSUE TITLE
Prepare the data to go into GitHub - Brittani & Jill

### ISSUE THREAD

**Issue by dlstrong** [data-carpentry-for-agriculture/trial-lesson#19]
Assign wrong projection, move, see what happens? (Other ideas possible)
- [x] Jill - look at shifting them all in Python in the same way
- [x] Brittani - verify outcome

**Comment by dlstrong** [comment]
- [ ] Jill - look at shifting them all in Python in the same way
- [ ] Brittani - verify outcome

**Comment by brittanikedge** [comment]
Jill shifted the files, Brittani checked that these were moved correctly and uploaded the new files in the data folder.
