### ISSUE TITLE
Track down and install software on ~5 loaner computers

### ISSUE THREAD

**Issue by dlstrong** [data-carpentry-for-agriculture/trial-lesson#20]
For anyone who (a) didn't bring one or (b) whose computer is not modern enough to handle things well

**Comment by dlstrong** [comment]
Update from Haeran: She doesn't know if she'll be able to give us any loaner computers or not. I may be able to get her to add a "Guest" account on my own work laptop, but that's only one.

**Comment by jnaiman** [comment]
Jill has 1 extra laptop and we have made sure that it works with the test install-script.

Someone can also use Jill's other laptop if need be.

**Comment by dlstrong** [comment]
2 loaner computers borrowed from Haeran, guest account added to Dena's work laptop. With those and Jill's extra we have 4 spares, and so far all correspondents replying to the survey have indicated that they're bringing their own laptops with enough drive space.
