### ISSUE TITLE
Lesson 3 st_write example is having problems

### ISSUE THREAD

**Issue by dlstrong** [data-carpentry-for-agriculture/trial-lesson#27]
Around 
st_write(spatial, "data/ssurgo.gpkg", layer_options = 'OVERWRITE=YES')

both the website example and the R Studio example aren't working. Screen shots in 1:54 pm Wednesday thread in Slack.

**Comment by dlstrong** [comment]
# Lesson 3 Exercise 1

planting <- read_sf("data/asplanted.gpkg")
st_crs(planting)
planting$geom
plantingutm <- st_transform_utm(planting)
st_crs(plantingutm)

# write file
st_write(boundaryutm, "boundary_utm.gpkg", layer_options = 'OVERWRITE=YES', update = TRUE)

# visualize
plot(boundary$geom)
map_poly(boundary, 'Type', 'Part of Field')

# SSURGO
boundary <- subset(boundary, Type == "Trial")
boundary.sp <- as(boundary, "Spatial")
ssurgo <- download_ssurgo("samplefield", boundary.sp)
# emergency backup
save (ssurgo, file = "ssurgo.Rdata")
# to load emergency backup
load (file = "ssurgo.Rdata")

# ssurgo data
names <- ssurgo$tabular$muaggatt 

# exercise
names

# merging and making consistent
spatial <- as(ssurgo$spatial, "sf")
spatial <- dplyr::rename(spatial, musym = MUSYM)
spatial <- merge(spatial, names, by = "musym")
head(spatial$muname)

# THIS ONE HAS ISSUES
st_write(spatial, "data/ssurgo.gpkg", layer_options = 'OVERWRITE=YES')

**Comment by jnaiman** [comment]
Fixed.
