### ISSUE TITLE
Functions.R -> installing from github

### ISSUE THREAD

**Issue by jnaiman** [data-carpentry-for-agriculture/trial-lesson#44]
In *theory* we don't have to go over all of the functions.R stuff if we make it into a github package and then have them use dev_tools to install our package: https://kbroman.org/pkg_primer/pages/github.html

**Comment by jnaiman** [comment]
@dlstrong should test this if we indeed go down this route :)

**Comment by jnaiman** [comment]
Also, we should make doc-strings for these functions

**Comment by dlstrong** [comment]
I really don't want to have to explain git to folks who have never programmed before. I know a dozen programmers who find it hair-tearingly frustrating.

**Comment by jnaiman** [comment]
Do not worry!  We will not have to!  In *theory* all you will add to any install is:

install.packages("devtools")
install_git("PATH TO OUR FUNCTIONS.R")

Because all dependencies are already installed on the USB drives, these will not to have to be re-installed, only devtools needs to be added.  

Of course, we will have to test my theory :)

**Comment by lvclark** [comment]
There's a little more to it than that, but not much.  I have a lot of
experience building R packages and could assist or advise (in the teeny
amounts of time I have available right now).

**Comment by lvclark** [comment]
You can also source from a url.

**Comment by jnaiman** [comment]
Oh yes!  A URL might be easiest of all.

And I'd assume we'd have to "package-ize" whatever we have if we want to use install_github?  We can assume everything is more complicated than I think it will be :D

**Comment by lvclark** [comment]
Yes, to use install_github it needs to be an actual package. Main
advantages are keeping clutter out of the global environment, and having
help pages for all functions. Sourcing from a url is definitely easier
though!

**Comment by dlstrong** [comment]
Here is where I think I have to rain on this parade: I am not going to sign myself up to take 20 working hard drives and spend 40 hours reproducing them by hand again in order to produce an alternative to two lines of code at the start of the scripts. 

If we're going to do this in the next two weeks, we HAVE to have more people than me on the thumb drive creation and testing and verification process. Otherwise it's really a non-starter for me. I did it the first time because there was no viable alternative. We do have a viable alternative now, which is to use the USBs as they are two weeks from now and do the experimentation after that.

**Comment by jnaiman** [comment]
I'm not 100% sure I'm following what the issue would be - this doesn't touch what is on the usbs at all.  The usb's have the packages.  The functions.R script is built *upon* those packages.  Nothing else is installed at all - once you source from a URL then it just loads from the functions.R like it would if you copied it into a script in RStudio and pressed the "Source" button.

Or are you talking about packagizing it?  I think the packagizing stuff would be a long-term goal, the sourcing from a URL is going to be easier than making them copy-paste again.

**Comment by dlstrong** [comment]
I posted this before we chatted during class, but I think it was a combination of me having the impression that what was being discussed with package-izing would require first reinstalling a master USB then making another master Box copy then reinstalling all the USBs, and then Yuanxi sent me an email with a link to a bunch of binaries in it which I think was for the "local download" option?

I just haven't got another 40 hours for soloing USB creation in the next two weeks if we also want to do significant things with reordering the sequence of the lessons between now and then.

**Comment by jnaiman** [comment]
Ah groovy, I think we are on the same page then as saving you and the students time!  *virtual high five*

:D

**Comment by jnaiman** [comment]
This is now handled in the install/download data script `package_load_and_test.R`
