### ISSUE TITLE
I think we need a Lesson 0 (or to bump all the lesson numbers up one)

### ISSUE THREAD

**Issue by dlstrong** [data-carpentry-for-agriculture/trial-lesson#5]
Right now, we're diving straight into "And this is a function and this is an argument" in lesson 1, when they may or may not even know what a function or argument are or why that even matters.

I think we need an introduction to the lesson entirely -- what is it we're trying to do? What will they learn, and what will they walk away with?  What is some basic vocabulary they'll absolutely need to know, gathered up in one place for easy reference? (And how much can we minimize the vocabulary needs and organize what we can't minimize?)

ETA, it looks like Neal has started a glossary -- how easy or hard is it to link words like function and argument to specific items in that list? (Could we make it as slick as Wikipedia, with link hovers popping up that definition?)

**Comment by jnaiman** [comment]
This should now (hopefully) be covered in:
 1. https://data-carpentry-for-agriculture.github.io/trial-lesson/00-Introduction/index.html
 1. https://data-carpentry-for-agriculture.github.io/trial-lesson/12-Introduction-To-Programming/index.html

**Comment by dlstrong** [comment]
dealt with!
