### ISSUE TITLE
New install & test process

### ISSUE THREAD

**Issue by jnaiman** [data-carpentry-for-agriculture/trial-lesson#55]
Step 1: set working directory
Step 2: source functions.R from the web
Step 3: use a "download_and_set_up_data" function that Jill will put into functions.R to create the "data" folder (OR plan to copy into whatever "data" folder is there) and download the data (we will probably need some sort of tryCatch here).
Step 4: have a "test_my_setup" function in functions.R that runs the setup script and *plots* results of tests so that the participants can compare their plot to our plot

**Comment by dlstrong** [comment]
We should make sure to update the instructions in the Intro to R lesson segment accordingly  - current theory is a manual copy and paste. We should do one manual copy and paste to get them used to creating and saving script files, but that one could be the package_load_and_test script which we're having them rename as startup?

**Comment by jnaiman** [comment]
Yes, but I think it can be even easier: like copy-paste the "setwd" command & copy-paste the "source functions.R" command and a "run test script" kind of command.  Save this as an R-script.

**Comment by jnaiman** [comment]
Also, add screenshots and more details about different windows in R!  I *feel* like I have this somewhere...

**Comment by jnaiman** [comment]
I'm moving this because I'm assuming we are still modifying the functions.R script.

**Comment by jnaiman** [comment]
This is now in the `download_data_test_script.R` file in episodes rmd with new functions in `functions.R`

Once tested I'm closing this :)

**Comment by jnaiman** [comment]
Tested, calling it done.
