### ISSUE TITLE
Install stick theory

### ISSUE THREAD

**Issue by dlstrong** [data-carpentry-for-agriculture/trial-lesson#67]
- [x] Brittani: Fix last boundary file and declare the data folder ready to copy
- [x] Dena: Update one USB with latest data 
- [x] Dena: Update QGIS install somehow, figure out what's wrong with it and how to make it better
- [x] Dena: Double check registration numbers
- [x] Dena: Get Neal an updated USB stick
- [x] Neal: Figure out how to automate the creation of the USB sticks
- [x] Figure out how to get the latest functions.R from the website based method (opt, can be copy-paste)
- [ ] Test it on Surface
- [x] If it works start mass production on the remaining 20 drives

**Comment by sigilante** [comment]
@dlstrong what's the status on the stick today?

**Comment by dlstrong** [comment]
Neal has 15-16, I have 15-16 - the others didn't copy right, but we should have enough to cover the class between us.

**Comment by dlstrong** [comment]
Marking this one for closure - we have a new method of updating the data based on pulling it from GitHub so it's OK that the USB data and catchup scripts are old.
