### ISSUE TITLE
Reordering sequence

### ISSUE THREAD

**Issue by dlstrong** [data-carpentry-for-agriculture/trial-lesson#69]
- [x] Brittani and Aolin do a reordering email draft or slack message
- [x] Group review the reorder theory
- [x] divide and conquer the implementation of reordering

**Comment by dlstrong** [comment]
Brittani laid out the order in Slack, here's the composited reshuffling for group consideration and commentary: https://docs.google.com/document/d/1wNjoRIHxDDo987jRUpKiI-ohcTeEAtynJkG5PzKNqAk/edit#

**Comment by jnaiman** [comment]
Reorg up, closing.
